input:
  files:
    - /Users/tarrynn/Desktop/bergamotte-app/log/development.log
    - /Users/tarrynn/Desktop/bergamotte-app/log/test.log
output:
  files:
    - ./tmp/out.txt
  elasticsearch:
    - http://docker:9200
